apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-encounter
spec:
  replicas: 1                # ðŸ‘ˆ antal pods
  selector:
    matchLabels:
      app: mysql-encounter
  template:
    metadata:
      labels:
        app: mysql-encounter
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpw
            - name: MYSQL_DATABASE
              value: encounterdb
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-encounter
spec:
  selector:
    app: mysql-encounter
  ports:
    - port: 3306
      targetPort: 3306
